name: sqflite_database_example
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path_provider: ^2.0.13

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # database storage
  sqflite: ^2.0.0+3

  # format DateTime
  intl: ^0.17.0

  # display todos in grid
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3

  widgets: ^1.4.5

  sqflite_common_ffi: ^2.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true